
export class ERR {
  public static CODE = {
    INVALID_REQUEST_BODY: 1,
    INVALID_SIGNATURE: 2,
    NOT_EXISTS: 3,
    AUTHENTICATION_FAILED: 4,
    ALREADY_EXISTS: 5,
    UPLOAD_FAIL: 6,
    TX_HASH_DUPLICATED: 7,
    INVALID_TX_HASH: 8,
    TOO_LONG_PARAMETER: 9,
    TOO_SHORT_PARAMETER: 10
  };
}
