/* GENERATED BY TYPECHAIN VER. 0.1.5-remake */
/* tslint:disable */

/**
 * https://github.com/dherges/ng-packagr/issues/217#issuecomment-339460255
 * Cannot call a namespace ('contract') Error fix
 */
import * as contractImported from 'truffle-contract';
const contract = contractImported;

import { BigNumber } from 'bignumber.js';
import {
  EtherAddress,
  EtherInteger,
  ITxParams,
  TruffleContract,
  TruffleContractInstance,
  TxValue
} from '../typechain-runtime';
export const BuiltContract = require('../../../../../muzika-contract/build/contracts/Dispatcher.json');

export interface IDispatcher extends TruffleContractInstance {}

export class Dispatcher extends TruffleContract<IDispatcher> {}

export const createTruffleDispatcher: () => Dispatcher = () =>
  contract(BuiltContract);
