/* GENERATED BY TYPECHAIN VER. 0.1.5-remake */
/* tslint:disable */

import * as contract from 'truffle-contract';
import { BigNumber } from 'bignumber.js';
import {
  EtherAddress,
  EtherInteger,
  ITxParams,
  RawAbiDefinition,
  TruffleContract,
  TruffleContractInstance,
  TxValue,
  promisify
} from '../typechain-runtime';
import BuiltContract from '../../../../../muzika-contract/build/contracts/Heritable.json';

export interface IHeritable extends TruffleContractInstance {
  owner(): Promise<string>;
  heir(): Promise<string>;
  heartbeatTimeout(): Promise<BigNumber>;
  timeOfDeath(): Promise<BigNumber>;

  transferOwnership: {
    (newOwner: EtherAddress, txParams?: ITxParams): Promise<void>;
    sendTransaction: (
      newOwner: EtherAddress,
      txParams?: ITxParams
    ) => Promise<void>;
    call: (newOwner: EtherAddress, txParams?: ITxParams) => Promise<void>;
    request: (newOwner: EtherAddress) => Promise<string>;
    estimateGas: (newOwner: EtherAddress) => Promise<number>;
  };
  setHeir: {
    (newHeir: EtherAddress, txParams?: ITxParams): Promise<void>;
    sendTransaction: (
      newHeir: EtherAddress,
      txParams?: ITxParams
    ) => Promise<void>;
    call: (newHeir: EtherAddress, txParams?: ITxParams) => Promise<void>;
    request: (newHeir: EtherAddress) => Promise<string>;
    estimateGas: (newHeir: EtherAddress) => Promise<number>;
  };
  removeHeir: {
    (txParams?: ITxParams): Promise<void>;
    sendTransaction: (txParams?: ITxParams) => Promise<void>;
    call: (txParams?: ITxParams) => Promise<void>;
    request: () => Promise<string>;
    estimateGas: () => Promise<number>;
  };
  proclaimDeath: {
    (txParams?: ITxParams): Promise<void>;
    sendTransaction: (txParams?: ITxParams) => Promise<void>;
    call: (txParams?: ITxParams) => Promise<void>;
    request: () => Promise<string>;
    estimateGas: () => Promise<number>;
  };
  heartbeat: {
    (txParams?: ITxParams): Promise<void>;
    sendTransaction: (txParams?: ITxParams) => Promise<void>;
    call: (txParams?: ITxParams) => Promise<void>;
    request: () => Promise<string>;
    estimateGas: () => Promise<number>;
  };
  claimHeirOwnership: {
    (txParams?: ITxParams): Promise<void>;
    sendTransaction: (txParams?: ITxParams) => Promise<void>;
    call: (txParams?: ITxParams) => Promise<void>;
    request: () => Promise<string>;
    estimateGas: () => Promise<number>;
  };
}

export const TruffleHeritable: () => TruffleContract<IHeritable> = () =>
  contract(BuiltContract);
