/* GENERATED BY TYPECHAIN VER. 0.1.5-remake */
/* tslint:disable */

import * as contract from 'truffle-contract';
import { BigNumber } from 'bignumber.js';
import {
  EtherAddress,
  EtherInteger,
  ITxParams,
  RawAbiDefinition,
  TruffleContract,
  TruffleContractInstance,
  TxValue
} from '../typechain-runtime';
import * as BuiltContract from '../../../../../muzika-contract/build/contracts/MuzikaPaperContract.json';

export interface IMuzikaPaperContract extends TruffleContractInstance {
  heartbeatTimeout(): Promise<BigNumber>;
  owner(): Promise<string>;
  heir(): Promise<string>;
  timeOfDeath(): Promise<BigNumber>;
  isPurchased(user: EtherAddress): Promise<boolean>;

  claimHeirOwnership: {
    (txParams?: ITxParams): Promise<void>;
    sendTransaction: (txParams?: ITxParams) => Promise<void>;
    call: (txParams?: ITxParams) => Promise<void>;
    request: () => Promise<string>;
    estimateGas: () => Promise<number>;
  };
  setHeir: {
    (newHeir: EtherAddress, txParams?: ITxParams): Promise<void>;
    sendTransaction: (
      newHeir: EtherAddress,
      txParams?: ITxParams
    ) => Promise<void>;
    call: (newHeir: EtherAddress, txParams?: ITxParams) => Promise<void>;
    request: (newHeir: EtherAddress) => Promise<string>;
    estimateGas: (newHeir: EtherAddress) => Promise<number>;
  };
  proclaimDeath: {
    (txParams?: ITxParams): Promise<void>;
    sendTransaction: (txParams?: ITxParams) => Promise<void>;
    call: (txParams?: ITxParams) => Promise<void>;
    request: () => Promise<string>;
    estimateGas: () => Promise<number>;
  };
  heartbeat: {
    (txParams?: ITxParams): Promise<void>;
    sendTransaction: (txParams?: ITxParams) => Promise<void>;
    call: (txParams?: ITxParams) => Promise<void>;
    request: () => Promise<string>;
    estimateGas: () => Promise<number>;
  };
  removeHeir: {
    (txParams?: ITxParams): Promise<void>;
    sendTransaction: (txParams?: ITxParams) => Promise<void>;
    call: (txParams?: ITxParams) => Promise<void>;
    request: () => Promise<string>;
    estimateGas: () => Promise<number>;
  };
  transferOwnership: {
    (newOwner: EtherAddress, txParams?: ITxParams): Promise<void>;
    sendTransaction: (
      newOwner: EtherAddress,
      txParams?: ITxParams
    ) => Promise<void>;
    call: (newOwner: EtherAddress, txParams?: ITxParams) => Promise<void>;
    request: (newOwner: EtherAddress) => Promise<string>;
    estimateGas: (newOwner: EtherAddress) => Promise<number>;
  };
  soldOut: {
    (txParams?: ITxParams): Promise<void>;
    sendTransaction: (txParams?: ITxParams) => Promise<void>;
    call: (txParams?: ITxParams) => Promise<void>;
    request: () => Promise<string>;
    estimateGas: () => Promise<number>;
  };
  purchase: {
    (txParams?: ITxParams): Promise<boolean>;
    sendTransaction: (txParams?: ITxParams) => Promise<boolean>;
    call: (txParams?: ITxParams) => Promise<boolean>;
    request: () => Promise<string>;
    estimateGas: () => Promise<number>;
  };
}

export const TruffleMuzikaPaperContract: () => TruffleContract<
  IMuzikaPaperContract
> = () => contract(BuiltContract);
