/* GENERATED BY TYPECHAIN VER. 0.1.5-remake */
/* tslint:disable */

import * as contract from 'truffle-contract';
import { BigNumber } from 'bignumber.js';
import {
  EtherAddress,
  EtherInteger,
  ITxParams,
  RawAbiDefinition,
  TruffleContract,
  TruffleContractInstance,
  TxValue,
  promisify
} from '../typechain-runtime';
import BuiltContract from '../../../build/contracts/ERC20Basic.json';

export interface IERC20Basic extends TruffleContractInstance {
  totalSupply(): Promise<BigNumber>;
  balanceOf(who: EtherAddress): Promise<BigNumber>;

  transfer: {
    (to: EtherAddress, value: EtherInteger, txParams?: ITxParams): Promise<
      boolean
    >;
    sendTransaction: (
      to: EtherAddress,
      value: EtherInteger,
      txParams?: ITxParams
    ) => Promise<boolean>;
    call: (
      to: EtherAddress,
      value: EtherInteger,
      txParams?: ITxParams
    ) => Promise<boolean>;
    request: (to: EtherAddress, value: EtherInteger) => Promise<string>;
    estimateGas: (to: EtherAddress, value: EtherInteger) => Promise<number>;
  };
}

export const TruffleERC20Basic: TruffleContract<IERC20Basic> = contract(
  BuiltContract
);
